### ISSUE TITLE
Fork syntax sugar

### ISSUE THREAD

**Issue by dmyyy** [Bluefinger/bevy_rand#10]
This is the way we fork an rng today

```
fn setup_source(mut commands: Commands, mut global: ResMut<GlobalEntropy<ChaCha8Rng>>) {
    commands
        .spawn((
            Source,
            EntropyComponent::from(&mut global),
        ));
}
```

It isn't super obvious what this does unless you're familiar with bevy_rand. It's a little bit more magic but I think it would be more understandable if it looked something like this

```
fn setup_source(mut commands: Commands, mut global_rng: ResMut<GlobalEntropy<ChaCha8Rng>>) {
    commands
        .spawn((
            Source,
            global_rng.fork(),
        ));
}
```

This can probably be done by adding

```
pub trait Forkable {
    fn fork(&mut self);
}
```

Or something rng specific since fork is usually used for async

```
pub trait ForkableRng {
    fn fork_rng(&mut self);
}
```

**Comment by Bluefinger** [comment]
I definitely can see something like this, and maybe we can make it so that any RNG that implements `RngCore` + `SeedableRng` is `ForkableRng` as well. It can even be an auto-trait, since I think the method will basically be the same for everything:

```rust
pub trait ForkableRng: RngCore + SeedableRng {
    fn fork(&mut self) -> Self;
}
```

The issue here is that forking is not just what is happening with the `GlobalEntropy` -> `EntropyComponent` seeding, we are doing a `From` as we are also creating a new type at the same time. Forking is a A to A transaction with the type being the same from both original and forked instance, what happens with the global seeding is A to B.

This doesn't mean we can't make things more magical, however, but it does mean we have to consider how we do this A to B transaction, which might require a further trait.

```rust
pub trait ForkableSource<T>: ForkableRng {
    type Output;

    fn fork_source(&self) -> Self::Output;
}
```

This one will have to be implemented for `GlobalEntropy` and `EntropyComponent` as we will need to describe how to do the A to B transactions: `GlobalEntropy` to `EntropyComponent`. I'm sure there can be even more trait magic that could be done here, but that's at least the basic layout of what would need to be done here.

**Comment by Bluefinger** [comment]
Playing around with some code has given me ideas for helper traits/methods, but basically they come in three forms:

- `fork`/`fork_rng` as a straight forking of the same underlying PRNG, like `GlobalEntropy<ChaCha8Rng>` -> `EntropyComponent<ChaCha8Rng>`.
- `fork_as` which allows you to set a different PRNG algorithm as the target so like `GlobalEntropy<ChaCha8Rng>` -> `EntropyComponent<WyRand>`
- `fork_inner` which forks the inner PRNG instance, so like `GlobalEntropy<ChaCha8Rng>` -> `ChaCha8Rng`.

However, I think I will need to be doing some rearchitecting of my trait soup to avoid situations like `EntropyComponent<EntropyComponent<ChaCha8Rng>>` from being able to occur. In any case, that's my idea for the forking APIs.

**Comment by Bluefinger** [comment]
@dmyyy I've created a PR #11 which you can look at and maybe even test on your end to see if it satisfies your idea for the forking API. It should simplify the three areas I see for forking RNGs within `bevy_rand`, and effectively deprecate the `From` implementations (which I will rethink their use-cases for a future version).

**Comment by dmyyy** [comment]
Thanks for the quick response! I'll try integrating into my codebase and let you know if I run into any issues

**Comment by dmyyy** [comment]
I think WyRand is missing some trait bounds you only added for ChaChaRng

```
the trait bound `bevy_rand::prelude::GlobalEntropy<WyRand>: Resource` is not satisfied
the trait bound `WyRand: bevy_prng::SeedableEntropySource` is not satisfied
the trait `bevy_prng::SeedableEntropySource` is not implemented for `WyRand`
```

**Comment by Bluefinger** [comment]
Uhh, how??? `bevy_prng` is all macros for the definitions of the newtyped PRNGs, so if ChaChaRng has it, so should WyRand o_O Perhaps you need to clean your dependencies? `bevy_prng` now has the `SeedableEntropySource` trait and that gets implemented to all the PRNGs there by means of macro. So it absolutely *should* have `SeedableEntropySource` implemented, and if it somehow doesn't, then something truly cursed is happening.

**Comment by dmyyy** [comment]
Cursed indeed - I tried replacing WyRand with ChaCha8Rng locally but that seems to have the same trait bound issues. Do I need to do something more than updating bevy_rand to test this?

```
bevy_rand = { git = "https://github.com/Bluefinger/bevy_rand", branch = "forking-refactor" }
# bevy_rand = "0.3"
```

Here's the repo (the main thing to look at is generation.rs). It worked with 0.3 and doesn't work with the new changes - not really sure what might be causing it. https://github.com/dmyyy/forking_issues/tree/forking_issues/src

**Comment by Bluefinger** [comment]
You need to update `bevy_prng` as well, so `bevy_prng = { version = "0.1", features = ["wyrand", "rand_chacha"] }` needs to point to a local version or the git version. I'm reconsidering requiring `bevy_prng` as a separate explicit dependency and wondering whether it is just better to roll it into `bevy_rand` and expose via features. It does lose the parallelisation of compilation though, but that kinda happens with `bevy_prng` and the algorithm crates, so... ¯\\\_(ツ)\_\/¯

**Comment by dmyyy** [comment]
Totally missed that bevy_prng needs to be updated to point to the branch as well - thanks for that. That fixed a bunch of the trait issues - however still seeing

```
error[E0277]: the trait bound `bevy_rand::prelude::GlobalEntropy<ChaCha8Rng>: Resource` is not satisfied
   --> src/generation.rs:39:53
    |
39  | fn generate(mut commands: Commands, mut global_rng: ResMut<GlobalEntropy<ChaCha8Rng>>) {
    |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Resource` is not implemented for `bevy_rand::prelude::GlobalEntropy<ChaCha8Rng>`
```

**Comment by Bluefinger** [comment]
I created a separate binary crate to load one of my examples in, while pointing to the git branch for the necessary dependencies. I was able to compile and run things just fine... I put the deps I needed to run the extracted example with the following:

```toml
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "1258ceb62cd8acb61f031dce128c2e04ee058538", version = "0.12.0-dev", default-features = false }
bevy_rand = { git = "https://github.com/Bluefinger/bevy_rand.git", package = "bevy_rand", branch = "forking-refactor" }
bevy_prng = { git = "https://github.com/Bluefinger/bevy_rand.git", package = "bevy_prng", branch = "forking-refactor", features = ["rand_chacha"] }
rand = "0.8"
```

And I simply copy-pasted my example code into `main.rs` and it was able to compile and run with the same result as on my branch. I will be making a further update to my PR to help simplify the dependency issue, though it will still require overriding the dependencies to point to the correct `bevy_prng` to test.

**Comment by dmyyy** [comment]
Looks like there's a bevy bug with AsyncComputeTask on that commit but fork_rng seems to be working fine
